version: "3" # version of docker compose to user
services:
  redis-server:
    image: 'redis'
  node-app:
    restart: always # restart if failed for any reasons
    build: .
    ports:
      - "4001:8081"

